DefaultSim:
  n_fish : 5
  title : Default Sim
  type: sim

  dynamics:
    max_lin_v : 5.0
    max_ang_v : 6.28
    lin_acc : 5.0
    ang_acc : 6.28
    fish_speed : 1.0
    wall_force : 1.0
    inter_force : 1.0
    robot_force : 1.0

  seed: null

  bounds:
    max_x : 32
    min_x : 0
    max_y : 18
    min_y : 0

DefaultReal:
  n_fish: 0
  title: Default Real
  type: real

  dynamics:
    max_lin_v: 0.4
    max_ang_v: 3.1415
    fish_speed: 1.0
    wall_force: 1.0
    inter_force: 1.0
    robot_force: 1.0

  seed: null

  transmitter_port: /dev/ttyACM0
  camera_port: 2
  camera_calibration_path: ../config/calibration.yaml
  robot_params_path: ../config/robot.yaml
  robot_detection_timeout: 1  # If during the episode the robot is not detected for this number of seconds, the episode is truncated
  robot_detection_reset_timeout: 10  # If while resetting the episode the robot is not detected for this number of seconds, an error is raised

FollowFishSim:
  from: DefaultSim
  n_fish: 1

  dynamics:
    max_lin_v: 0.2
    max_ang_v: 3.1415
    lin_acc : 0.4
    ang_acc : 6.2830
    fish_speed : 0.0
    wall_force : 0.0
    inter_force : 0.0
    robot_force : 0.0

  bounds:
    max_x: 0.74269172
    min_x: 0
    max_y: 0.44522103
    min_y: 0

FollowFishReal:
  from: DefaultReal
  n_fish: 1

  dynamics:
    max_lin_v: 0.2
    max_ang_v: 3.1415
    fish_speed : 0.0
    wall_force : 0.0
    inter_force : 0.0
    robot_force : 0.0
