Default:
  n_fish : 5
  title : "plot_title"

  dynamics:
    max_lin_v : 5.0
    max_ang_v : 6.28
    lin_acc : 5.0
    ang_acc : 6.28
    fish_speed : 1.0
    wall_force : 1.0
    inter_force : 1.0
    robot_force : 1.0


  seed : null

  bounds:
    max_x : 32
    min_x : 0
    max_y : 18
    min_y : 0

Test:
  from: Default
  fish_speed: 10